
name: gpt-c
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - python>=3.9.1
  - pip
  - tqdm
  - cudnn
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
    - jax
    - jaxlib==0.1.70+cuda111
    - torch==1.9.0+cu111
    - torchvision
    - dm-haiku
    - optax
    - ftfy 
    - regex
    - lm_dataformat
    - tensorflow
    - einops
    - smart_open[gcs]
    - wandb
    - google-cloud-storage